<?php


/**
 * @file
 * Provider of WADL helper constants and methods
 *
 */
class WADL
{
  // Define XML "method" constants
  const APPLICATION     = 'wadl:application';
  const DOC             = 'wadl:doc';
  const RESOURCES       = 'wadl:resources';
  const RESOURCE        = 'wadl:resource';
  const METHOD          = 'wadl:method';
  const REPRESENTATION  = 'wadl:representation';
  const PARAM           = 'wadl:param';
  const REQUEST         = 'wadl:request';
}

